// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_eucafSvpX2CuC1L8X-w1_7m0RPPVQY8',
    appId: '1:871374110316:web:3badbedf4fd9c02aaae249',
    messagingSenderId: '871374110316',
    projectId: 'voice-hub-c78e2',
    authDomain: 'voice-hub-c78e2.firebaseapp.com',
    storageBucket: 'voice-hub-c78e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKsBhdLvbq2OeHrudbEyQupEOihg3LII',
    appId: '1:871374110316:android:9d072ce242ec22eaaae249',
    messagingSenderId: '871374110316',
    projectId: 'voice-hub-c78e2',
    storageBucket: 'voice-hub-c78e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRg7JIh_uytQtBhz8FReW2uykL00vonQ',
    appId: '1:871374110316:ios:b0a4e19a85d2c23faae249',
    messagingSenderId: '871374110316',
    projectId: 'voice-hub-c78e2',
    storageBucket: 'voice-hub-c78e2.firebasestorage.app',
    iosBundleId: 'com.example.voiceHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRg7JIh_uytQtBhz8FReW2uykL00vonQ',
    appId: '1:871374110316:ios:b0a4e19a85d2c23faae249',
    messagingSenderId: '871374110316',
    projectId: 'voice-hub-c78e2',
    storageBucket: 'voice-hub-c78e2.firebasestorage.app',
    iosBundleId: 'com.example.voiceHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_eucafSvpX2CuC1L8X-w1_7m0RPPVQY8',
    appId: '1:871374110316:web:592de1054730683baae249',
    messagingSenderId: '871374110316',
    projectId: 'voice-hub-c78e2',
    authDomain: 'voice-hub-c78e2.firebaseapp.com',
    storageBucket: 'voice-hub-c78e2.firebasestorage.app',
  );
}
